/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfirmedInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getDeletedInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markInquiryAsConfirmed' : IDL.Func([IDL.Nat], [], []),
  'markInquiryAsDeleted' : IDL.Func([IDL.Nat], [], []),
  'submitAndContinueOnWhatsApp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfirmedInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getDeletedInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markInquiryAsConfirmed' : IDL.Func([IDL.Nat], [], []),
    'markInquiryAsDeleted' : IDL.Func([IDL.Nat], [], []),
    'submitAndContinueOnWhatsApp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'id' : IDL.Nat, 'timestamp' : Time })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };