/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'location' : string,
  'eventDate' : string,
  'eventType' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmedInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getDeletedInquiries' : ActorMethod<[], Array<Inquiry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryAsConfirmed' : ActorMethod<[bigint], undefined>,
  'markInquiryAsDeleted' : ActorMethod<[bigint], undefined>,
  'submitAndContinueOnWhatsApp' : ActorMethod<
    [string, string, string, string, string, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    { 'id' : bigint, 'timestamp' : Time }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];